name: Update YouTube IPTV Playlist

on:
  schedule:
    - cron: "0 */4 * * *"  # Runs every 4 hours (e.g., 0:00, 4:00, 8:00, etc.)
  workflow_dispatch:        # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the GITHUB_TOKEN write access to push changes
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper git history

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg
          pip install yt-dlp

      - name: Generate Playlist
        run: |
          chmod +x update_playlist.sh
          # Continue on error to handle individual channel failures
          ./update_playlist.sh > youtube_live.m3u || echo "Some channels failed, but continuing..."

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add youtube_live.m3u
          
          # Only commit if there are changes
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
